apiVersion: v1
kind: Service
metadata:
  name: service-client-lb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
