apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    service: server
spec:
  type: ClusterIP # Regular service for client access
  ports:
    - port: 8000
      targetPort: 8000
      name: server
  selector:
    app: server